export const Path = {
  main: "/",
  login: "/login",
  passwordReset: "/password-reset",
  signUp: "/sign-up",
  landing: "/course",
  profile: "/profile",
  myCourse: "/my-course",
  admin: "/admin",
  courseDetail: "/admin/course",
  landingDetail: "/admin/landing",
  userDetail: "/admin/user",
  authorDetail: "/admin/author",
  adminLandings: "/admin/landings",
  adminUsers: "/admin/users",
};
