# frontend/Dockerfile.dev

FROM node:22-alpine

# Установка рабочей директории
WORKDIR /app

# Копирование package.json и package-lock.json
COPY package.json package-lock.json ./

# Установка зависимостей
RUN npm install

# Копирование исходного кода
COPY ./src ./src
COPY ./public ./public

# Установка переменных окружения для React
ENV CHOKIDAR_USEPOLLING=true

# Команда запуска разработческого сервера
CMD ["npm", "run", "dev"]
