FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf

# Копируем конфиг
COPY ./prod.conf /etc/nginx/conf.d/default.conf

# Папка под сертификаты (необязательно)
RUN mkdir -p /etc/nginx/certs

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
