FROM nginx:stable-alpine

# Удалим дефолтный конфиг (по желанию)
RUN rm /etc/nginx/conf.d/default.conf

# Копируем наш prod.conf в дефолтное место
COPY ./prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
