"""Final models

Revision ID: 95db47233cd9
Revises: aff1e3b91c14
Create Date: 2025-02-01 16:00:41.409264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '95db47233cd9'
down_revision: Union[str, None] = 'aff1e3b91c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.create_table('landing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('EN', 'ES', 'RU', name='lang_enum'), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.Column('main_image', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('main_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_id'), 'landing', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_table('landing_authors',
    sa.Column('landing_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['landing_id'], ['landing.id'], ),
    sa.PrimaryKeyConstraint('landing_id', 'author_id')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_video_link', sa.String(length=500), nullable=True),
    sa.Column('full_video_link', sa.String(length=500), nullable=True),
    sa.Column('program_text', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.add_column('courses', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('courses', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('courses', 'title')
    op.drop_column('courses', 'created_at')
    op.drop_column('courses', 'price')
    op.drop_column('courses', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('courses', sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('courses', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('courses', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('courses', 'description')
    op.drop_column('courses', 'name')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_table('landing_authors')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_landing_id'), table_name='landing')
    op.drop_table('landing')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
