"""Add slug

Revision ID: f40fc671e3a0
Revises: 81090525b514
Create Date: 2025-02-11 14:32:14.905882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40fc671e3a0'
down_revision: Union[str, None] = '81090525b514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landing', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landing', 'slug')
    # ### end Alembic commands ###
