"""Добавлен новый столбец в таблицу XYZ

Revision ID: f7b71177b0e2
Revises: f40fc671e3a0
Create Date: 2025-02-11 19:45:11.559537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b71177b0e2'
down_revision: Union[str, None] = 'f40fc671e3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
